@echo off
setlocal

set "SIDOFUN_NEWSROOM_PRESET=%SIDOFUN_NEWSROOM_PRESET%"
if not defined SIDOFUN_NEWSROOM_PRESET set "SIDOFUN_NEWSROOM_PRESET=newsroom-5"

set "SIDOFUN_NEWSROOM_GAP=%SIDOFUN_NEWSROOM_GAP%"
if not defined SIDOFUN_NEWSROOM_GAP set "SIDOFUN_NEWSROOM_GAP=16"

set "SIDOFUN_NEWSROOM_STARTUP_DELAY_MS=%SIDOFUN_NEWSROOM_STARTUP_DELAY_MS%"
if not defined SIDOFUN_NEWSROOM_STARTUP_DELAY_MS set "SIDOFUN_NEWSROOM_STARTUP_DELAY_MS=1500"

set "SIDOFUN_NEWSROOM_SETTLE_DELAY_MS=%SIDOFUN_NEWSROOM_SETTLE_DELAY_MS%"
if not defined SIDOFUN_NEWSROOM_SETTLE_DELAY_MS set "SIDOFUN_NEWSROOM_SETTLE_DELAY_MS=3000"

set "SIDOFUN_NEWSROOM_TARGETS_FILE=%SIDOFUN_NEWSROOM_TARGETS_FILE%"
if not defined SIDOFUN_NEWSROOM_TARGETS_FILE set "SIDOFUN_NEWSROOM_TARGETS_FILE=examples/workflows/newsroom-layout.targets.json"

bun run examples/workflows/run-newsroom-layout.ts --targets-file %SIDOFUN_NEWSROOM_TARGETS_FILE% --preset %SIDOFUN_NEWSROOM_PRESET% --gap %SIDOFUN_NEWSROOM_GAP% --startup-delay-ms %SIDOFUN_NEWSROOM_STARTUP_DELAY_MS% --settle-delay-ms %SIDOFUN_NEWSROOM_SETTLE_DELAY_MS% %*
