import { z } from 'zod';

export const desktopActionValues = [
  'click',
  'drag_mouse',
  'move_mouse',
  'scroll',
  'type',
  'key_press',
  'screenshot',
  'screenshot_raw',
  'screenshot_all',
  'screenshot_secondary',
  'screenshot_win32',
  'screen_size',
  'mouse_position',
  'active_window',
  'get_screen_size',
  'get_mouse_position',
  'launch_application',
  'focus_window',
  'show_window',
  'hide_window',
  'close_window',
  'maximize_window',
  'minimize_window',
  'restore_window',
  'set_mouse_delay',
  'key_toggle',
  'type_delayed',
  'set_keyboard_delay',
  'highlight',
  'get_active_window',
  'get_window_rect',
  'get_window_info',
  'list_processes',
  'list_windows',
  'move_window',
  'resize_window',
  'drag_window_move',
  'drag_window_resize',
  'get_clipboard',
  'set_clipboard',
  'clipboard_read',
  'clipboard_write',
  'clipboard_clear',
  'clipboard_status',
  'desktop_scope_create',
  'desktop_scope_list',
  'desktop_scope_info',
  'desktop_scope_focus',
  'desktop_scope_screenshot',
  'desktop_scope_click',
  'desktop_scope_type',
  'desktop_scope_close',
  'session_create',
  'session_list',
  'session_info',
  'session_touch',
  'session_resources',
  'session_resource_owners',
  'session_claim_resource',
  'session_own_resource',
  'session_release_resource',
  'session_close',
  'session_list_idle',
  'session_reap_idle',
  'trace_start',
  'trace_list',
  'trace_info',
  'trace_add_metadata',
  'trace_record',
  'trace_export',
  'trace_stop',
  'trajectory_start',
  'trajectory_list',
  'trajectory_info',
  'trajectory_append_turn',
  'trajectory_export',
  'trajectory_stop',
  'shell_run',
  'shell_run_cmd',
  'shell_run_pwsh',
  'terminal_spawn',
  'terminal_list',
  'terminal_status',
  'terminal_focus',
  'terminal_type',
  'terminal_exec',
  'terminal_close',
  'opencli_status',
  'hf_papers_status',
  'browser_extension_status',
  'browser_extension_capabilities',
  'browser_extension_sites',
  'browser_extension_wait_provider',
  'browser_extension_workspace_list',
  'browser_extension_workspace_get',
  'browser_extension_workspace_set',
  'browser_extension_workspace_clear',
  'browser_extension_session_create',
  'browser_extension_session_list',
  'browser_extension_session_info',
  'browser_extension_session_refresh',
  'browser_extension_session_reconnect',
  'browser_extension_session_close',
  'browser_extension_session_nuke',
  'browser_extension_session_wait_ready',
  'browser_extension_queue_clear',
  'browser_extension_tabs',
  'browser_extension_frames',
  'browser_extension_navigate',
  'browser_extension_focus_tab',
  'browser_extension_snapshot',
  'browser_extension_dom_tree',
  'browser_extension_screenshot',
  'browser_extension_inspect',
  'browser_extension_inspect_all',
  'browser_extension_locate',
  'browser_extension_click_query',
  'browser_extension_links',
  'browser_extension_actionables',
  'browser_extension_page_state',
  'browser_extension_next_actions',
  'browser_extension_markdown',
  'browser_extension_readability',
  'browser_extension_evaluate',
  'browser_extension_click',
  'browser_extension_type',
  'browser_extension_press',
  'browser_extension_editor_read',
  'browser_extension_editor_fill',
  'browser_extension_form_fill',
  'browser_extension_form_fill_human',
  'browser_extension_form_fill_many',
  'browser_extension_form_fields',
  'browser_extension_form_contexts',
  'browser_extension_form_find_field',
  'browser_extension_form_radio_groups',
  'browser_extension_form_radio_select',
  'browser_extension_form_segmented_options',
  'browser_extension_form_segmented_select',
  'browser_extension_form_toggle',
  'browser_extension_form_range_set',
  'browser_extension_form_options',
  'browser_extension_form_fill_label',
  'browser_extension_form_fill_query',
  'browser_extension_form_select',
  'browser_extension_form_upload',
  'browser_extension_form_combobox_options',
  'browser_extension_form_combobox_select',
  'browser_extension_form_submit',
  'browser_extension_form_submit_wait',
  'browser_extension_auth_login',
  'browser_extension_auth_signup',
  'browser_extension_query_plan',
  'browser_extension_query_workflow',
  'browser_extension_cookies',
  'browser_extension_x_search',
  'browser_extension_x_timeline',
  'browser_extension_x_bookmarks',
  'browser_extension_x_notifications',
  'browser_extension_x_messages',
  'browser_extension_x_open_message_thread',
  'browser_extension_x_send_message',
  'browser_extension_x_read_thread',
  'browser_extension_x_post',
  'browser_extension_x_open_post',
  'browser_extension_x_profile',
  'browser_extension_x_follow',
  'browser_extension_x_reply',
  'browser_extension_x_like',
  'browser_extension_x_repost',
  'browser_extension_chatgpt_list_conversations',
  'browser_extension_chatgpt_open_conversation',
  'browser_extension_chatgpt_new_chat',
  'browser_extension_chatgpt_sidebar_state',
  'browser_extension_chatgpt_toggle_sidebar',
  'browser_extension_chatgpt_models',
  'browser_extension_chatgpt_select_model',
  'browser_extension_chatgpt_info',
  'browser_extension_chatgpt_conversation_actions',
  'browser_extension_chatgpt_conversation_action',
  'browser_extension_chatgpt_rename_conversation',
  'browser_extension_chatgpt_stop',
  'browser_extension_chatgpt_continue',
  'browser_extension_chatgpt_response_controls',
  'browser_extension_chatgpt_previous_response',
  'browser_extension_chatgpt_next_response',
  'browser_extension_chatgpt_list_response_versions',
  'browser_extension_chatgpt_select_response_version',
  'browser_extension_chatgpt_regenerate',
  'browser_extension_chatgpt_edit_message',
  'browser_extension_chatgpt_read_thread',
  'browser_extension_chatgpt_read_message',
  'browser_extension_chatgpt_current_conversation',
  'browser_extension_chatgpt_export_thread',
  'browser_extension_chatgpt_read_latest',
  'browser_extension_chatgpt_send',
  'browser_extension_chatgpt_ask',
  'browser_extension_chatgpt_ask_thread',
  'browser_extension_chatgpt_rewrite_thread',
  'browser_extension_chatgpt_wait_idle',
  'browser_extension_chatgpt_wait_response',
  'browser_extension_chatgpt_wait_message',
  'browser_extension_chatgpt_wait_sidebar',
  'browser_extension_chatgpt_wait_model',
  'browser_extension_chatgpt_wait_conversation',
  'browser_extension_chatgpt_prepare',
  'browser_extension_chatgpt_delete_conversation',
  'browser_extension_chatgpt_archive_conversation',
  'browser_extension_deepseek_list_conversations',
  'browser_extension_deepseek_open_conversation',
  'browser_extension_deepseek_new_chat',
  'browser_extension_deepseek_sidebar_state',
  'browser_extension_deepseek_toggle_sidebar',
  'browser_extension_deepseek_models',
  'browser_extension_deepseek_select_model',
  'browser_extension_deepseek_info',
  'browser_extension_deepseek_conversation_actions',
  'browser_extension_deepseek_conversation_action',
  'browser_extension_deepseek_rename_conversation',
  'browser_extension_deepseek_stop',
  'browser_extension_deepseek_continue',
  'browser_extension_deepseek_response_controls',
  'browser_extension_deepseek_previous_response',
  'browser_extension_deepseek_next_response',
  'browser_extension_deepseek_list_response_versions',
  'browser_extension_deepseek_select_response_version',
  'browser_extension_deepseek_regenerate',
  'browser_extension_deepseek_edit_message',
  'browser_extension_deepseek_read_thread',
  'browser_extension_deepseek_read_message',
  'browser_extension_deepseek_current_conversation',
  'browser_extension_deepseek_export_thread',
  'browser_extension_deepseek_read_latest',
  'browser_extension_deepseek_send',
  'browser_extension_deepseek_ask',
  'browser_extension_deepseek_ask_thread',
  'browser_extension_deepseek_rewrite_thread',
  'browser_extension_deepseek_wait_idle',
  'browser_extension_deepseek_wait_response',
  'browser_extension_deepseek_wait_message',
  'browser_extension_deepseek_wait_sidebar',
  'browser_extension_deepseek_wait_model',
  'browser_extension_deepseek_wait_conversation',
  'browser_extension_deepseek_prepare',
  'browser_extension_deepseek_delete_conversation',
  'browser_extension_deepseek_archive_conversation',
  'browser_extension_network_events',
  'browser_extension_dom_events',
  'browser_extension_clear_network_events',
  'browser_extension_clear_dom_events',
  'browser_extension_session_events',
  'browser_extension_clear_session_events',
  'browser_extension_wait_dom_quiet',
  'browser_extension_wait_network_idle',
  'browser_extension_wait_page_stable',
  'browser_extension_wait_url',
  'browser_extension_wait_selector',
  'browser_extension_wait_no_selector',
  'browser_extension_wait_text',
  'browser_extension_provider_register',
  'browser_extension_provider_heartbeat',
  'browser_extension_provider_state_upsert',
  'browser_extension_provider_events_upsert',
  'browser_extension_provider_poll',
  'browser_extension_provider_command_result',
  'opencli_doctor',
  'hf_papers_doctor',
  'opencli_sites',
  'opencli_commands',
  'opencli_run',
  'opencli_workspace_list',
  'opencli_workspace_get',
  'opencli_workspace_set',
  'opencli_workspace_clear',
  'opencli_workspace_bind_session',
  'opencli_workspace_unbind_session',
  'opencli_workspace_session',
  'hf_papers_search',
  'hf_papers_info',
  'hf_papers_read',
  'hf_papers_list_daily',
  'twitter_search',
  'twitter_timeline',
  'twitter_bookmarks',
  'twitter_post',
  'local_coder_list',
  'local_coder_status',
  'local_coder_open',
  'local_coder_focus',
  'local_coder_close',
  'local_coder_maximize',
  'local_coder_minimize',
  'local_coder_restore',
  'local_coder_move',
  'local_coder_resize',
  'local_coder_run'
] as const;

export const browserIdValues = [
  'chrome',
  'firefox',
  'edge',
  'brave',
  'opera',
  'vivaldi',
  'chromium',
  'maxthon',
  'midori',
  'min',
  'netsurf'
] as const;

export const browserAutomationActionValues = [
  'browser_list',
  'browser_info',
  'browser_profiles',
  'browser_launch_plan',
  'browser_launch',
  'browser_windows',
  'browser_focus_window',
  'browser_runtime_create',
  'browser_runtime_list',
  'browser_runtime_info',
  'browser_runtime_close',
  'browser_page_list',
  'browser_page_open',
  'browser_page_info',
  'browser_page_navigate',
  'browser_page_click',
  'browser_page_fill',
  'browser_page_press',
  'browser_page_wait_for',
  'browser_page_evaluate',
  'browser_page_content',
  'browser_page_screenshot',
  'browser_page_pdf',
  'browser_page_download_url',
  'browser_page_network_events',
  'browser_page_events',
  'browser_page_console_events',
  'browser_page_clear_events',
  'browser_page_wait_for_network',
  'browser_page_close'
] as const;

export const automationActionValues = [
  ...desktopActionValues,
  ...browserAutomationActionValues
] as const;

export const streamTypeValues = [
  'screenshot',
  'window_change',
  'clipboard',
  'process',
  'browserext_tabs',
  'browserext_snapshot',
  'browserext_screenshot',
  'browserext_session_events',
  'browserext_network_events',
  'browserext_dom_events'
] as const;

export const queryTypeValues = [
  'active_window',
  'screen_size',
  'mouse_position'
] as const;

export const cmdActionValues = [
  'spawn',
  'attach',
  'exec',
  'type',
  'press',
  'screenshot',
  'break',
  'eof',
  'close',
  'list',
  'tabs',
  'find',
  'get_info',
  'status',
  'focus',
  'activate_by_title',
  'new_tab',
  'next_tab',
  'prev_tab',
  'split_vertical',
  'split_horizontal',
  'pane_up',
  'pane_down',
  'pane_left',
  'pane_right'
] as const;

export const DesktopActionTypeEnum = z.enum(desktopActionValues);
export const BrowserIdEnum = z.enum(browserIdValues);
export const BrowserAutomationActionEnum = z.enum(browserAutomationActionValues);
export const AutomationActionEnum = z.enum(automationActionValues);
export const StreamTypeEnum = z.enum(streamTypeValues);
export const QueryTypeEnum = z.enum(queryTypeValues);
export const CMDActionEnum = z.enum(cmdActionValues);

export const CoordinatesSchema = z.object({
  x: z.number(),
  y: z.number()
});

export const PointerButtonEnum = z.enum(['left', 'right', 'middle']);

export const DesktopActionSchema = z.object({
  type: DesktopActionTypeEnum,
  coordinates: CoordinatesSchema.optional(),
  button: PointerButtonEnum.default('left'),
  path: z.array(CoordinatesSchema).optional(),
  direction: z.enum(['up', 'down', 'left', 'right']).optional(),
  count: z.number().default(1),
  text: z.string().optional(),
  key: z.string().optional(),
  format: z.enum(['png', 'jpg']).default('png'),
  application: z.string().optional(),
  args: z.array(z.string()).optional(),
  windowTitle: z.string().optional(),
  processName: z.string().optional(),
  delay: z.number().optional(),
  duration: z.number().optional(),
  opacity: z.number().optional(),
  cpm: z.number().optional(),
  windowHandle: z.number().optional(),
  width: z.number().optional(),
  height: z.number().optional(),
  x: z.number().optional(),
  y: z.number().optional(),
  filename: z.string().optional(),
  returnBase64: z.boolean().optional(),
  scale: z.union([z.string(), z.number()]).optional(),
  config: z.record(z.string(), z.unknown()).optional(),
  command: z.string().optional(),
  cwd: z.string().optional(),
  workspace: z.string().optional(),
  keepBrowserOpen: z.boolean().optional(),
  maximizeBrowser: z.boolean().optional(),
  waitAfterMs: z.number().optional(),
  env: z.record(z.string(), z.string()).optional(),
  timeoutMs: z.number().optional(),
  targetUrl: z.string().optional(),
  selector: z.string().optional(),
  query: z.string().optional(),
  expression: z.string().optional(),
  value: z.string().optional(),
  email: z.string().optional(),
  username: z.string().optional(),
  password: z.string().optional(),
  confirmPassword: z.string().optional(),
  fullName: z.string().optional(),
  skipSubmit: z.boolean().optional(),
  humanLike: z.boolean().optional(),
  delayMs: z.number().optional(),
  jitterMs: z.number().optional(),
  by: z.enum(['text', 'value', 'label']).optional(),
  match: z.enum(['exact', 'includes']).optional(),
  exact: z.boolean().optional(),
  filepath: z.string().optional(),
  fileName: z.string().optional(),
  fileData: z.string().optional(),
  mimeType: z.string().optional(),
  lastModified: z.number().optional(),
  fields: z.array(z.object({
    selector: z.string(),
    value: z.string(),
    frameSelectors: z.array(z.string()).optional()
  })).optional(),
  frameSelectors: z.array(z.string()).optional(),
  waitUrlIncludes: z.string().optional(),
  waitText: z.string().optional(),
  waitSelector: z.string().optional(),
  waitNoSelector: z.string().optional(),
  intervalMs: z.number().optional(),
  urlIncludes: z.string().optional(),
  method: z.string().optional(),
  maxVersions: z.number().optional(),
  mutationType: z.enum(['childList', 'attributes', 'characterData']).optional(),
  textIncludes: z.string().optional(),
  sites: z.array(z.string()).optional(),
  protocolVersion: z.string().optional(),
  browserName: z.string().optional(),
  browserVersion: z.string().optional(),
  userAgent: z.string().optional(),
  extensionId: z.string().optional(),
  tabs: z.array(z.record(z.string(), z.unknown())).optional(),
  networkEvents: z.array(z.record(z.string(), z.unknown())).optional(),
  domEvents: z.array(z.record(z.string(), z.unknown())).optional(),
  events: z.array(z.record(z.string(), z.unknown())).optional(),
  snapshot: z.record(z.string(), z.unknown()).optional(),
  commandId: z.string().optional(),
  ok: z.boolean().optional(),
  shell: z.enum(['cmd', 'pwsh']).optional(),
  kind: z.enum(['cmd', 'pwsh']).optional(),
  sessionId: z.string().optional(),
  tabId: z.number().optional(),
  ownerSessionId: z.string().optional(),
  scopeId: z.string().optional(),
  traceId: z.string().optional(),
  trajectoryId: z.string().optional(),
  turnId: z.string().optional(),
  windowHandles: z.array(z.number()).optional(),
  processIds: z.array(z.number()).optional(),
  titleQuery: z.string().optional(),
  name: z.string().optional(),
  clientKind: z.enum(['operator', 'python', 'mcp', 'http', 'websocket', 'internal']).optional(),
  resourceType: z.enum(['terminal', 'browser_runtime', 'browser_page', 'desktop_scope', 'trace', 'trajectory']).optional(),
  resourceId: z.string().optional(),
  takeover: z.boolean().optional(),
  metadata: z.record(z.string(), z.unknown()).optional(),
  cleanupOwnedResources: z.boolean().optional(),
  maxIdleMs: z.number().optional(),
  source: z.enum(['platform', 'terminal', 'browser']).optional(),
  operation: z.string().optional(),
  status: z.enum(['success', 'error']).optional(),
  durationMs: z.number().optional(),
  input: z.unknown().optional(),
  output: z.unknown().optional(),
  error: z.record(z.string(), z.unknown()).optional(),
  role: z.string().optional(),
  prompt: z.unknown().optional(),
  response: z.unknown().optional(),
  actions: z.array(z.unknown()).optional(),
  screenshots: z.array(z.unknown()).optional(),
  timestamp: z.string().optional()
});

export const BrowserLaunchSchema = z.object({
  profile: z.string().optional(),
  profilePath: z.string().optional(),
  url: z.string().optional(),
  privateMode: z.boolean().optional(),
  headless: z.boolean().optional(),
  args: z.array(z.string()).optional(),
  detached: z.boolean().optional()
});

export const BrowserWindowFocusSchema = z.object({
  handle: z.number().optional(),
  titleIncludes: z.string().optional()
});

export type DesktopActionType = z.infer<typeof DesktopActionTypeEnum>;
export type BrowserIdValue = z.infer<typeof BrowserIdEnum>;
export type BrowserAutomationActionValue = z.infer<typeof BrowserAutomationActionEnum>;
export type AutomationActionValue = z.infer<typeof AutomationActionEnum>;
export type StreamTypeValue = z.infer<typeof StreamTypeEnum>;
export type QueryTypeValue = z.infer<typeof QueryTypeEnum>;
export type CMDActionValue = z.infer<typeof CMDActionEnum>;
